"""Add roles to user model

Revision ID: 4f1d6631e4e9
Revises: f3a7c9d2e114
Create Date: 2026-09-25 11:56:31.125835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f1d6631e4e9'
down_revision: Union[str, Sequence[str], None] = 'f3a7c9d2e114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('role', sa.VARCHAR(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'role')
    # ### end Alembic commands ###
