"""Add password hash

Revision ID: c0c41b085961
Revises: 1062ab1a63c9
Create Date: 2026-09-10 19:26:24.407899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "c0c41b085961"
down_revision: Union[str, Sequence[str], None] = "1062ab1a63c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Users", sa.Column("password_hash", sa.String(), nullable=False))
    op.drop_column("Users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Users",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("Users", "password_hash")
    # ### end Alembic commands ###
